/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.codefish.fixturefeedpro;

public final class R {
    public static final class array {
        public static final int channels=0x7f060004;
        public static final int espn_channels=0x7f060006;
        public static final int feedbacktypelist=0x7f060000;
        public static final int listChannels=0x7f060001;
        public static final int search_exclude=0x7f060003;
        public static final int search_words=0x7f060002;
        public static final int sky_channels=0x7f060005;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int defaults=0x7f010002;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int preferenceKey=0x7f010000;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int preferenceValKey=0x7f010001;
    }
    public static final class bool {
        public static final int allow_alternate_source=0x7f080000;
    }
    public static final class color {
        public static final int highlight_colour=0x7f090000;
        public static final int normal_colour=0x7f090001;
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int bbc_one=0x7f020001;
        public static final int bbc_redbutton=0x7f020002;
        public static final int bbc_three=0x7f020003;
        public static final int bbc_two=0x7f020004;
        public static final int calendar=0x7f020005;
        public static final int clear=0x7f020006;
        public static final int espn=0x7f020007;
        public static final int feedback=0x7f020008;
        public static final int five=0x7f020009;
        public static final int four=0x7f02000a;
        public static final int icon=0x7f02000b;
        public static final int itv_1=0x7f02000c;
        public static final int itv_2=0x7f02000d;
        public static final int itv_3=0x7f02000e;
        public static final int itv_4=0x7f02000f;
        public static final int refresh=0x7f020010;
        public static final int refresh_icon=0x7f020011;
        public static final int settings=0x7f020012;
        public static final int sky_sports1=0x7f020013;
        public static final int sky_sports2=0x7f020014;
        public static final int sky_sports3=0x7f020015;
    }
    public static final class id {
        public static final int ButtonSendFeedback=0x7f0b0006;
        public static final int EditTextFeedbackBody=0x7f0b0005;
        public static final int EditTextName=0x7f0b0002;
        public static final int EditTextTwitter=0x7f0b0003;
        public static final int LinearLayout01=0x7f0b0007;
        public static final int ListView01=0x7f0b0008;
        public static final int ScrollView01=0x7f0b0000;
        public static final int SpinnerFeedbackType=0x7f0b0004;
        public static final int TextViewTitle=0x7f0b0001;
        public static final int ad=0x7f0b0009;
        public static final int bottomtext=0x7f0b000e;
        public static final int calIcon=0x7f0b000c;
        public static final int feedbackButton=0x7f0b0010;
        public static final int icon=0x7f0b000b;
        public static final int refreshButton=0x7f0b000f;
        public static final int row=0x7f0b000a;
        public static final int settingButton=0x7f0b0011;
        public static final int toptext=0x7f0b000d;
    }
    public static final class integer {
        public static final int days_to_keep_data=0x7f070001;
        public static final int max_threads=0x7f070000;
        public static final int refresh_interval_mins=0x7f070002;
    }
    public static final class layout {
        public static final int feedback_form=0x7f030000;
        public static final int main=0x7f030001;
        public static final int row=0x7f030002;
    }
    public static final class menu {
        public static final int menu=0x7f0a0000;
    }
    public static final class string {
        /**  END Feedback 
         */
        public static final int app_name=0x7f050005;
        /**  Feedback 
         */
        public static final int email_address=0x7f050000;
        public static final int feedbacktype1=0x7f050001;
        public static final int feedbacktype2=0x7f050002;
        public static final int feedbacktype3=0x7f050003;
        public static final int feedbacktype4=0x7f050004;
        public static final int request_extension=0x7f050008;
        public static final int request_url=0x7f050007;
        public static final int save_file=0x7f050009;
        public static final int welcome_message=0x7f050006;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a ListPreferenceMultiSelect.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ListPreferenceMultiSelect_defaults org.codefish.fixturefeedpro:defaults}</code></td><td></td></tr>
           <tr><td><code>{@link #ListPreferenceMultiSelect_preferenceKey org.codefish.fixturefeedpro:preferenceKey}</code></td><td></td></tr>
           <tr><td><code>{@link #ListPreferenceMultiSelect_preferenceValKey org.codefish.fixturefeedpro:preferenceValKey}</code></td><td></td></tr>
           </table>
           @see #ListPreferenceMultiSelect_defaults
           @see #ListPreferenceMultiSelect_preferenceKey
           @see #ListPreferenceMultiSelect_preferenceValKey
         */
        public static final int[] ListPreferenceMultiSelect = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>This symbol is the offset where the {@link org.codefish.fixturefeedpro.R.attr#defaults}
          attribute's value can be found in the {@link #ListPreferenceMultiSelect} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:defaults
        */
        public static final int ListPreferenceMultiSelect_defaults = 2;
        /**
          <p>This symbol is the offset where the {@link org.codefish.fixturefeedpro.R.attr#preferenceKey}
          attribute's value can be found in the {@link #ListPreferenceMultiSelect} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:preferenceKey
        */
        public static final int ListPreferenceMultiSelect_preferenceKey = 0;
        /**
          <p>This symbol is the offset where the {@link org.codefish.fixturefeedpro.R.attr#preferenceValKey}
          attribute's value can be found in the {@link #ListPreferenceMultiSelect} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:preferenceValKey
        */
        public static final int ListPreferenceMultiSelect_preferenceValKey = 1;
    };
}
